import React from "react";
import Head from "next/head";
function PageHead() {
  return (
    <Head>
      <title>Modal Card Generator</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@200;400;500;600;700;800&family=Roboto:wght@100;300;400;500;700&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@500;800&family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@200;400;500;600;700;800&family=Roboto:wght@100;300;400;500;700&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
}

export default PageHead;
